# Generated by Django 2.1 on 2018-08-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('descricao',)},
        ),
    ]
