version: '3'

services:
  db:
    image: mysql:5.7
    environment: 
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=easy2make"
    restart: "always"
    ports: 
      - "3306:3306"
  web:
    build: .
    image: "easy2make"
    ports: 
      - "8000:8000"
    entrypoint: /easy2make/entrypoint.sh
    restart: "always"
    depends_on:
      - db
    links:   
      - db:db
