# Generated by Django 2.1 on 2018-08-22 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_telefone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='telefone_number',
            new_name='telefone',
        ),
    ]
